import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";

import { ContentViewer } from "@/components/content-viewer";
import { Gameboy } from "@/components/gameboy";
import { Navbar } from "@/components/navbar";

import "./globals.css";

const dogicaPixel = localFont({ src: "../fonts/Dogica_Pixel.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          dogicaPixel.className,
          "min-h-screen bg-[#24242A] bg-[url('/bg.png')] bg-cover bg-center bg-no-repeat",
        )}
      >
        <main className="flex-col p-7 lg:flex lg:flex-row lg:gap-10 lg:p-20">
          <div>
            <Gameboy />
          </div>
          <div className="grow">
            <div className="flex flex-col gap-4">
              <Navbar />
              <ContentViewer />
            </div>
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
